name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
env:
  PROJECT_NAME: "ticketking"
  PORT: "8081"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    # properties 설정
    - name: Setup application properties
      run: |
        echo "${{ secrets.APPLICATION_PROPERTIES }}" >> src/main/resources/application.properties
        mkdir -p src/main/resources/protected
        echo "${{ secrets.KAKAOMAP_PROPERTIES }}" >> src/main/resources/protected/kakaomap.properties
        echo "${{ secrets.OAUTH_PROPERTIES }}" >> src/main/resources/protected/oauth.properties
        echo "${{ secrets.DATA_API_PROPERTIES }}" >> src/main/resources/protected/data_api.properties
        echo "${{ secrets.EMAIL_PROPERTIES }}" >> src/main/resources/protected/email.properties
        echo "${{ secrets.PORTONE_PROPERTIES }}" >> src/main/resources/protected/portone.properties
        
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set Docker image tag
      run: echo "IMAGE_TAG=ticket-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}:${IMAGE_TAG} .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}:${IMAGE_TAG}
          
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}:${IMAGE_TAG}
          docker stop ${{ env.PROJECT_NAME }} || true
          docker rm ${{ env.PROJECT_NAME }} || true
          docker run -d --name ${{ env.PROJECT_NAME }} -p ${{ env.PORT }}:${{ env.PORT }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}:${IMAGE_TAG}
